apiVersion: apps/v1
kind: Deployment
metadata:
  name: okutery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okutery
  template:
    metadata:
      labels:
        app: okutery
    spec:
      containers:
      - image: okteto.dev/okutery:latest
        name: okutery
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "30d58031-2018-4953-b5a0-3c4ec05a2617"
        - name: Vless_Path
          value: "/30d58031-2018-4953-b5a0-3c4ec05a2617-vl"
        - name: Vmess_UUID
          value: "30d58031-2018-4953-b5a0-3c4ec05a2617"
        - name: Vmess_Path
          value: "/30d58031-2018-4953-b5a0-3c4ec05a2617-vm"
        - name: Share_Path
          value: "/v2lirerk"
